app = "ssh-portfolio-qingchen"
primary_region = "hkg"

[build]

[http_service]
  # We don't serve HTTP, disable it
  internal_port = 23234
  force_https = false
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = "tcp"
  internal_port = 23234

  [[services.ports]]
    port = 22

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

[vm]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
